# Generated by Django 2.2.4 on 2019-08-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabseServerProps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=500)),
                ('dbname', models.CharField(max_length=500)),
                ('user_name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('schema_name', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
